### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by DerKnerd** [dahlbyk/FSRazor#1]
I am asking, because I would like to build a web page with just F#. If it is dead, could you give me hints to build my own version?

**Comment by dahlbyk** [comment]
You're more than welcome to take this and run with it - I've added you to the project, and we can move to a more appropriate organization if it takes off. I'm not aware of any other Razor implementations of an F# provider, and we don't really need more than one.

Assuming you still want to work with the ASP.NET 4 stack, the boilerplate to integrate into the stack doesn't look like it has changed much: [`RazorCodeLanguage`](https://aspnetwebstack.codeplex.com/SourceControl/latest#src/System.Web.Razor/RazorCodeLanguage.cs).

Razor vNext does look quite a bit different: [`RazorCodeLanguage`](https://github.com/aspnet/Razor/blob/dev/src/Microsoft.AspNet.Razor/RazorCodeLanguage.cs).

**Comment by jeroldhaas** [comment]
I'd love to contribute to this project as well.

**Comment by dahlbyk** [comment]
Sold.

If you haven't seen the (4.5-year-old!) introduction post:
https://lostechies.com/keithdahlby/2011/02/07/fsharp-plus-razor-view-engine-equals-fsrazor/

**Comment by jeroldhaas** [comment]
![excellent](http://gifrific.com/wp-content/uploads/2013/04/Mr-Burns-Saying-Excellent.gif)

I suppose first step would be to set the project up into a project scaffold type structure and get some tests configured?

Probably would be good to configure forks for each ASP.NET stack (freshen 3, update to 4, integrate OWIN/5 support), too?

**Comment by dahlbyk** [comment]
I wonder if it would make sense to have a single solution with projects for each MVC version, a la [Glimpse](https://github.com/Glimpse/Glimpse/tree/master/source)? From a test maintainability standpoint, there's probably an opportunity to share test `.fshtml` files between test projects targeting each version.

**Comment by jeroldhaas** [comment]
I think that's a very sensible solution layout, more so than individual project branches. So, to clarify, do you think there should be separate namespaces consumed for FSRazor based on supported MVC version? I noticed that's how Glimpse is organized.

This can still be accomplished, too, when using Project Scaffold based solutions.

I really like the idea of shared test code among the different MVC version branches. Code reuse is a thing, after all :wink:

I don't see any test code in the current revision, however it appears there's some [test code available in the Razor repository](https://github.com/aspnet/Razor/tree/dev/test).

Since the discussion is moving off the issue's main title, I've made a new issue #2 with better focus.
